### PR TITLE
Code restructure and Bernstein polynomials.

### PR DESCRIPTION
**Pull request by J15525**
I updated the structure of the polynomials, updated the naming, and this branch also contains the bulk of the Bernstein polynomial additions. (Perhaps a bit too many changes for one branch.)

To be specific, I changed the following:
Type-wise:
- Renamed abstract type `GenericPolynomials` to `AbstractPolynomials`.
- Renamed abstract type `NodalPolynomials` to `AbstractLagrangePolynomials`.
(Let me know if you all agree with these names, this is not (yet) set in stone. In particular, if these polynomials always constitute a basis, we could rename that to something like `(Abstract)PolynomialBasis`.)
Functions:
- Made sure that all `AbstractPolynomials` are callable (that is, all instances of types that are subtypes of this AbstractType are callable). Note that this calls an `evaluate` function. If that function in not defined, a `MethodError` will be raised.
- The evaluate function which @dtoshniwal will implement is currently located in the BernsteinPolynomial file. You can change this to your algorithm, but please make sure that the name and first two arguments are consistent with the other `evaluate` functions.
Naming:
- I updated all occurrences of the old name that I could find (related to issue #3 and #4), and made sure that the changes of #4 are already included in this branch as well. @apalha, could you check if the one remaining reference to the old name that I could find, which is in the CI link in the `README.md` file, can be changed? I think you set this up when creating the repo.
Other:
- I removed the `@time` macro from the testing files.
- I added some comments here and there. If anyone feels there should be more comments, please add them.

Some general comments:
- I realised that while the general method to call the polynomials is nice, the Lagrange and Bernstein polynomials are defined on different intervals, so we have to think about how we want to make that clear.
- I think that @dccabanas used `assert` for some checks, though `assert` is meant for development checks. This means that it can be turned of depending on the level of compiler optimisation and may not even work in future releases if you are not in debug mode. So I suggest we use standard if checks to catch things we want to check for the user. This also allows us to create more appropriate error messages if needed. Of course, `assert` can be nice as a development tool.
- Some parts of the code now use unicode characters such as $\xi$. Do we want to use this or not?
- As there is a lot going on in this pull-request, I assigned all of use and requested everyone to review the pull-request before it can be merged.

### CODE REVIEW

**Review by dccabanas — APPROVED** [review]

**Comment by apalha** [comment]
I will look into this tomorrow.

**Comment by dtoshniwal** [comment]
I added the new Bernstein polynomial and derivative evaluator. @J15525, could you please check and update BernsteinPolynomialTests.jl accordingly? Thanks!

**Review by dtoshniwal — CHANGES_REQUESTED** [review]
The only change needed now is to modify the tests according to the new evaluator for Bernstein polynomials.

PS: The red color here looks sooo aggressive :(

**Comment by apalha** [comment]
I made the following (minor) changes:

- Changed NodalPolynomials to LagrangePolynomials.
- Updates the README.md file to account for the new name.

Regarding the (argument) checks I propose using:  [ArgCheck.jl](https://github.com/jw3126/ArgCheck.jl)

My advise is to add argument checks, but not to be excessive because if we have a tiny function that computes one element of an array and we are doing checks, it is overkill and will slow down the code.

In the coming days I will make another pull request to add the remaining mimetic elements and derivatives. I will also compute n-derivatives, but this is a bit irrelevant because we will never use it for these basis functions.

**Pull request merged**
